import prisma from '../lib/prisma';
import { NotFoundError } from '../lib/errors';

export const payrollsService = {
  async getPayrolls(query: any = {}) {
    const { period, staffId, status } = query;
    const where: any = {};
    if (period) where.period = period;
    if (staffId) where.staffId = Number(staffId);
    if (status) where.status = status;

    return prisma.payroll.findMany({
      where,
      include: { staff: true }
    });
  },

  async generatePayrolls(period: string) {
    const staffs = await prisma.staff.findMany({ where: { status: 'ACTIVE' } });
    
    // Parse period to calculate start and end dates for the given month 'YYYY-MM'
    const [year, month] = period.split('-').map(Number);
    const startDate = new Date(year, month - 1, 1);
    const endDate = new Date(year, month, 1);

    return prisma.$transaction(async (tx) => {
      // 1. Delete existing payroll records for this period to maintain idempotence
      await tx.payroll.deleteMany({
        where: { period }
      });

      // 2. Generate new payroll records based on actual payments in the selected period
      const results = [];
      for (const staff of staffs) {
        const payments = await tx.paymentHistory.aggregate({
          _sum: { discountedPrice: true },
          where: {
            trainerId: staff.id,
            date: {
              gte: startDate,
              lt: endDate
            },
            status: 'COMPLETED'
          }
        });

        const periodRevenue = payments._sum.discountedPrice || 0;
        
        // Base salary is 2,000,000 KRW
        // Incentive is 10% of the actual revenue generated by the staff in this period
        const baseSalary = 2000000;
        const incentive = periodRevenue * 0.1;
        
        const payroll = await tx.payroll.create({
          data: {
            staffId: staff.id,
            period,
            baseSalary,
            incentive,
            total: baseSalary + incentive,
            status: 'PENDING'
          }
        });
        results.push(payroll);
      }

      // 3. Keep the Staff lifetime revenue cached field up-to-date
      for (const staff of staffs) {
        const totalPayments = await tx.paymentHistory.aggregate({
          _sum: { discountedPrice: true },
          where: {
            trainerId: staff.id,
            status: 'COMPLETED'
          }
        });
        await tx.staff.update({
          where: { id: staff.id },
          data: {
            revenue: totalPayments._sum.discountedPrice || 0
          }
        });
      }

      return results;
    });
  },

  async updatePayrollStatus(id: number, status: string) {
    return prisma.payroll.update({
      where: { id },
      data: { status }
    }).catch(() => {
      throw new NotFoundError('Payroll not found');
    });
  }
};
